### ISSUE TITLE
[Reopen] Latest update broke NUT integration

### ISSUE THREAD

**Issue by sblantipodi** [hassio-addons/addon-nut#106]
**The problem**

this is a reopen of this: #46481 and this #91

Hi,
as soon as I updated the nut add-on my UPS started having problems with home assistant.

After some hours it stops working, it seems that it stops communicating with HA.

This is the error I have in the logs
[Cyberpower_PR1500ELCD@localhost] failed - Data stale
92136.307299	Poll UPS 

Restarting the host makes it working again for some hours until I get the same error

**What is version of Home Assistant Core has the issue?**

2021.2.3

**What was the last working version of Home Assistant Core?**

 2021.2.3

**What type of installation are you running?**

Home Assistant OS

**Integration causing the issue**

NUT v0.6.1 and later

**Link to integration documentation on our website**

https://www.home-assistant.io/integrations/nut/

**Example YAML snippet**

```yaml
users:
  - username: admin
    password: mypwd
    instcmds:
      - all
    actions: []
devices:
  - name: Cyberpower_PR1500ELCD
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
list_usb_devices: true
upsd_maxage: 25 // tried 30 and same problem
upsmon_deadtime: 25 // tried 30 and same problem

```

**Anything in the logs that might be useful for us?**

```txt
[Cyberpower_PR1500ELCD@localhost] failed - Data stale
92136.307299	Poll UPS 
```

Using a Cyperpower PR1500ELCD and it worked fine since months until the last update.

This is a reopen of this: #46481 and this #91

Please be sure that the issue is fixed before closing it :)

**Comment by sinclairpaul** [comment]
Please add the poll interval as advised previously and as other users have reported.

```
devices:
  - name: Cyberpower
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
```

The addon wraps the nut packages distributed by Debian.
