### ISSUE TITLE
Cannot set pollinterval in ups.conf

### ISSUE THREAD

**Issue by tjdavis3** [hassio-addons/addon-nut#108]
# Problem/Motivation

Cannot set the global `pollinterval` parameter for ups.conf

## Expected behavior

upsd default is 2s which causes issues with some USB UPSes as described under Known Issues and Bugs on this page:  https://networkupstools.org/docs/man/usbhid-ups.html.  The fix is to set the global pollinterval setting.

## Actual behavior

There is no way to set any of the global directives in ups.conf

## Steps to reproduce

Configure a UPS that exhibits the issue (Cyberpower OR700LCDRM1Ua)

## Proposed changes

Add an option for `ups_pollinterval` to be set in ups.conf before creating the device entries.

**Comment by sinclairpaul** [comment]
It's a device/driver parameter, for example:
```
devices:
  - name: Cyberpower
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
 ```
