### ISSUE TITLE
Lost connection after recent update

### ISSUE THREAD

**Issue by JohnnyPicnic** [hassio-addons/addon-nut#13]
After applying the update 5 days ago I haven't been able to get connected to my UPS.
I thought maybe it was an issue with the usb being disconnect from my vm machine but that is not the case.

```
Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 79fe9c6
 You are running the latest version of this add-on.
 System: HassOS 2.12  (amd64 / qemux86-64)
 Home Assistant version: 0.103.0
 Supervisor version: 192
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[19:50:21] INFO: Setting mode to netserver...
[19:50:21] INFO: Generating /etc/nut/upsd.users...
[19:50:21] INFO: Configuring user: nut
[19:50:21] DEBUG: Password SHA1: 24118455D6BA570A87BEC4A9EBDADBE70D8ADBB3
[19:50:21] DEBUG: Requested API resource: https://api.pwnedpasswords.com/range/24118
[19:50:21] DEBUG: API HTTP Response code: 200
[19:50:21] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[19:50:22] INFO: Configuring Device named myups...
[19:50:22] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892
   0.000000	Starting UPS: myups
Network UPS Tools - Generic HID driver 0.41 (3.8.0-3220-g866b921892)
Using subdriver: MGE HID 1.39
USB communication driver 0.33
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:50:23] INFO: Starting the UPS information server...
Network UPS Tools upsd 3.8.0-3220-g866b921892
   0.000000	fopen /var/run/nut/upsd.pid: No such file or directory
   0.000297	listening on 0.0.0.0 port 3493
   0.000747	Connected to UPS [myups]: usbhid-ups-myups
[19:50:23] INFO: Starting the UPS Monitor...
Network UPS Tools upsmon 3.8.0-3220-g866b921892
   0.000000	fopen /var/run/upsmon.pid: No such file or directory
   0.000252	Using power down flag file /etc/killpower
   0.000439	UPS: myups@localhost (master) (power value 1)
   0.000527	debug level is '1'
   0.005219	Trying to connect to UPS [myups@localhost]
   0.015902	User upsmonmaster@127.0.0.1 logged into UPS [myups]
   0.006455	Logged into UPS myups@localhost
```

```
2019-12-11 19:55:22 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.nut
2019-12-11 19:55:22 ERROR (SyncWorker_2) [homeassistant.components.nut.sensor] Failure getting NUT ups alias, Socket error.
2019-12-11 19:55:22 ERROR (SyncWorker_2) [homeassistant.components.nut.sensor] NUT Sensor has no data, unable to set up
2019-12-11 19:55:22 WARNING (MainThread) [homeassistant.components.sensor] Platform nut not ready yet. Retrying in 90 seconds.
```

**Comment by sinclairpaul** [comment]
The NUT processes in the addon are connected to your UPS, the issue is in the HA integration communicating with it.  How do you have the integration configured?

**Comment by JohnnyPicnic** [comment]
```
- platform: nut
  username: nut
  password: nut85
  resources:
    - ups.status
    - ups.load
    - battery.runtime
    - battery.charge
    - battery.charge.low
    - input.voltage
    - ups.temperature
    - ups.status.display
    - ups.mfr
    - ups.delay.shutdown
    - ups.vendorid
    - ups.timer.shutdown
    - ups.test.result
    - ups.firmware
    - ups.serial
    - ups.productid
    - battery.type
    - ups.beeper.status
    - input.transfer.low
    - input.transfer.high
    - input.voltage.nominal
    - output.current
    - output.frequency
    - output.voltage
    - output.voltage.nominal
```
