### ISSUE TITLE
Poll UPS fasiled - Data stale

### ISSUE THREAD

**Issue by arandax** [hassio-addons/addon-nut#134]
# Problem/Motivation

Nut stops getting data from UPS after some time
## Expected behavior

Data read from UPS

## Actual behavior

UPS is APC BACK-UPS RS 550G (BR550GI), connected via USB to HASS VM (ESXi) 
Registry entry:
95803.323656	Poll UPS [myups@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4

## Steps to reproduce

Here is my config:

```
users:
  - username: <user>
    password: <password>
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
mode: netserver
shutdown_host: 'false'
upsd_maxage: 25
upsmon_deadtime: 25
```

## Proposed changes

Already tried upsmon_deadtime: 25 , don't know how to fix this.
