### ISSUE TITLE
Secrets are not getting called from the config:

### ISSUE THREAD

**Issue by Salvora** [hassio-addons/addon-nut#174]
# Problem/Motivation

I have tried to add a secret for the secName but it didn't work.

## Expected behavior

It should have been called to replace the value.

## Actual behavior

I have checked the supervisor logs but I didn't see any log like this "INFO (MainThread) [supervisor.homeassistant.secrets] Request secret snmpv3_nut_username".
I haven't tried with privPassword and authPassword yet.
**Edit:** Tried with privPassword  and authPassword. They also don't work with secrets.
I have tried reloading the supervisor, and restarting the Host but no luck. Using plain text works but using secrets does not work.

## Steps to reproduce

Use a config like below and try to add a secret to the secName. Add the corresponding entry to the secrets.yaml too. 
Start NUT. 
NUT crashes and you cannot see any supervisor log for calling the secret.
```
users:
  - username: '!secret nut_username'
    password: '!secret nut_password'
    instcmds:
      - all
    actions: []
devices:
  - name: UPS
    driver: snmp-ups
    port: 192.168.1.62
    config:
      - snmp_version = v3
      - secLevel = noAuthNoPriv
      - secName = "!secret snmpv3_nut_username"
      - desc = "APC UPS SRT5KXLI"
mode: netserver
shutdown_host: 'false'

```
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
