### ISSUE TITLE
Polling interval too slow.

### ISSUE THREAD

**Issue by sblantipodi** [hassio-addons/addon-nut#18]
# Problem/Motivation

> Polling interval is too slow and there is no configuration for it

## Expected behavior

> Have some sort of configuration to configure the polling interval

Using Cyberpower SmartUPS PR1500ELCD

**Comment by sinclairpaul** [comment]
Please elaborate on the issue you are facing, share your config, and specify what change you believe is necessary.

**Comment by sblantipodi** [comment]
> Please elaborate on the issue you are facing, share your config, and specify what change you believe is necessary.

this is my configution

```
sensor:
  - platform: nut
    name: "CyberPower PR1500ELCD"
    host: 40817795-nut
    username: user
    password: !secret nut
    resources:
      - ups.status.display
      - ups.timer.reboot
      - battery.voltage
      - ups.firmware.aux
      - ups.mfr
      - battery.runtime.low
      - ups.delay.shutdown
      - ups.load
      - ups.realpower.nominal
      - battery.charge.warning
      - battery.charge.low
      - ups.vendorid
      - ups.timer.shutdown
      - ups.test.result
      - ups.firmware
      - ups.productid
      - battery.runtime
      - battery.type
      - ups.model
      - ups.beeper.status
      - battery.charge
      - input.sensitivity
      - input.transfer.low
      - input.transfer.high
      - input.voltage
      - input.voltage.nominal
      - input.transfer.reason
      - output.current
      - output.frequency
      - output.voltage
      - output.voltage.nominal
```

and this is the addon config:

```
{
  "users": [
    {
      "username": "admin",
      "password": "XXX",
      "instcmds": [
        "all"
      ],
      "actions": []
    }
  ],
  "devices": [
    {
      "name": "myups",
      "driver": "usbhid-ups",
      "port": "auto",
      "config": []
    }
  ],
  "mode": "netserver",
  "shutdown_hassio": "false"
}
```

Love this addon so much, thanks guys.

I would like to have a config option to update the sensor value more often that the default one.
It seems that my sensors is updated every 30 seconds more or less, I would like to update it every 10 seconds at least.

Is it possible to add a parameter in the configuration to configure the polling interval (how often the sensor is updated)?
