### ISSUE TITLE
Server and client. UPS Management

### ISSUE THREAD

**Issue by DivanX10** [hassio-addons/addon-nut#204]
Home Assistant OS 6.6
Core 2021.11.5
Supervisor 2021.10.8
Add-on: Network UPS Tools version: 0.9.0

***

This is an introduction and purely so that you understand what works for me and what I'm trying to configure in the NUT addon. First read below, so you will see that I have no problems with access to the UPS and I can manage the UPS, but I can only manage with Home Assistant on OpenWRT, and with OS Home Assistant it does not work.

***
For understanding, I will show you and describe below what works for me and why I want to do the same on OS Home Assistant. On the OpenWRT OS, I have a Home Assistant and there are nut packages and I can send commands to control the UPS, and I can also receive data from the UPS.

**Home Assistant on OpenWRT** 
![image](https://user-images.githubusercontent.com/64090632/143869019-44ed1ec4-e949-425c-a139-f538588251b8.png)

**List of available commands for UPS control**

```
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 calibrate.start
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 calibrate.stop
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.disable
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.enable
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.mute
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.off
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.on
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 load.off
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 load.off.delay
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 load.on
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 load.on.delay
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 shutdown.return
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 shutdown.stayoff
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 shutdown.stop
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 test.battery.start.deep
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 test.battery.start.quick
upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 test.battery.stop
```

**All commands are processed and I get statuses from sensors**
![image](https://user-images.githubusercontent.com/64090632/143870704-0b8897a0-0418-418b-9d1a-c188f18cac99.png)

**I made a control panel for the UPS** 
![image](https://user-images.githubusercontent.com/64090632/143868379-1cab5af9-95b4-4f1e-a44c-b1817c09070c.png)
```
switch: 
- platform: command_line
  switches:
    ups_beeper: 
      command_on: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.enable
      command_off: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.disable
      command_state: upsc ups@192.168.1.200 ups.beeper.status
      value_template: '{{ is_state("sensor.ups_beeper_status","enabled") }}'
      friendly_name: 'Звуковое оповещение'

    ups_test_battery_deep:
      command_on: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 test.battery.start.deep
      command_off: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 test.battery.stop
      command_state: upsc ups@192.168.1.200 ups.status
      value_template: '{{ states("sensor.ups_self_test_result") == "In progress" }}'
      friendly_name: 'Полный тест батареи'

    ups_test_battery_quick:
      command_on: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 test.battery.start.quick
      command_off: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 test.battery.stop
      command_state: upsc ups@192.168.1.200 ups.status
      value_template: '{{ states("sensor.ups_self_test_result") == "In progress" }}'
      friendly_name: 'Быстрый тест батареи'
```

**Added UPS via GUI NUT integration**
![image](https://user-images.githubusercontent.com/64090632/143867275-9064f4aa-1322-4a1b-9f6d-92395d68f5ff.png)
![image](https://user-images.githubusercontent.com/64090632/143867316-23b70ad0-527d-4bfe-aa7b-a15f370f26d2.png)
![image](https://user-images.githubusercontent.com/64090632/143867352-d2eac959-8581-43aa-8c41-65636b7ce66c.png)

***

Now let's get to the heart of the problem. The UPS is connected to the Synology NAS, and the Home Assistant runs on a virtual machine in the Synology NAS and does not have access to the UPS via a USB cable. I would like to send commands from Home Assistant to control the UPS, but I can't do this because OS Home Assistant runs on Linix Alpine OS, and it doesn't have a NUT package. I can't even run this command `upsc' through the terminal ups@192.168.1.200 `.

![image](https://user-images.githubusercontent.com/64090632/143867953-fa1f34d2-1ef1-48f4-ab06-76024c53ae08.png)

I installed the NUT addon, specified the following config and the launch was successful. I'm trying to connect via GUI integration to the NUT addon and get rejected. Tell me, how can I configure the NUT addon so that I can send commands to control the UPS and have sensors?

In the configuration , I specified the following

```
devices:
  - config: []
    driver: snmp-ups
    name: ups
    port: 192.168.1.200
mode: netclient
shutdown_host: 'false'
users:
  - actions: []
    instcmds:
      - all
    password: nutuser
    username: nut!user
remote_ups_host: 192.168.1.200
remote_ups_name: ups
remote_ups_user: hassmon
remote_ups_password: '12345678'
```

The following is displayed in the log
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (amd64 / qemux86-64)
 Home Assistant Core: 2021.11.5
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[15:11:51] INFO: Setting mode to netclient...
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:11:52] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000287	Using power down flag file /etc/killpower
   0.000495	UPS: ups@192.168.1.200 (slave) (power value 1)
   0.000639	debug level is '1'
   0.000779	Warning: running as one big root process by request (upsmon -p)
   0.001013	Init SSL without certificate database
   0.001906	Trying to connect to UPS [ups@192.168.1.200]
   0.003780	Logged into UPS ups@192.168.1.200
```

**I'm trying to connect to the NUT addon and I get this error**
![image](https://user-images.githubusercontent.com/64090632/143871538-0c4e764d-77e1-4aa6-b78e-af1598d12dcc.png)
![image](https://user-images.githubusercontent.com/64090632/143871561-7cc0aef6-4c90-4340-94b6-9f7227221a98.png)

**Comment by sinclairpaul** [comment]
You have the mode set to netclient, which means the NUT server process won't be running (this is to attach to another NUT instance).  If you do have NUT running elsewhere, point the integration at that (I don't believe the integration supports sending commands however).

As for the upsc commands, it is not an addon issue, however Alpine does have a NUT package on it's edge repo.

**Comment by DivanX10** [comment]
By the way, yes, I didn't think about edge, I'll look for it, but unfortunately, if I find it and install it, then there is a problem.  the fact is that after installing the package, it flies off after restarting HA OS and you need to install it again. I forgot to write to you about the lower option and it doesn't work for me. Specified 'snmp-ups' as the driver. I thought that this addon would allow you to control the UPS using commands. Tell me, is it possible to add to the addon the ability to send commands to the UPS?

```
devices:
  - config: []
    driver: snmp-ups
    name: ups
    port: 192.168.1.200
mode: netserver
shutdown_host: 'false'
users:
  - actions: []
    instcmds:
      - all
    password: hass20ups
    username: nutups
```

Что пишется в логах
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (amd64 / qemux86-64)
 Home Assistant Core: 2021.11.5
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[17:06:12] INFO: Setting mode to netserver...
[17:06:12] INFO: Generating /etc/nut/upsd.users...
[17:06:12] INFO: Configuring user: nutups
[17:06:12] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[17:06:12] INFO: Configuring Device named ups...
[17:06:12] INFO: Starting the UPS drivers...
Created directory: /var/lib/snmp/cert_indexes
Startup timer elapsed, continuing...
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
