### ISSUE TITLE
UPS devices become unavailable every 8 - 14 hours randomly

### ISSUE THREAD

**Issue by DanDon** [hassio-addons/addon-nut#206]
I have 2 x Cyberpower UPS devices connected to HA OS via usb and the supervisor added with this configuration:

```
devices:
  - name: UPS1
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
  - name: UPS2
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
mode: netserver
shutdown_host: 'false'
users:
  - username: ups
    password: ******
    instcmds:
      - all
    actions: []
list_usb_devices: true
upsd_maxage: 25
upsmon_deadtime: 25
```

But every now and then, sometimes twice or three times a day, the devices become unavailable. My current fix is to have this automation in place:

```
alias: UPS Refresh
description: ''
trigger:
  - platform: state
    entity_id: sensor.ups_load
    to: unavailable
  - platform: state
    entity_id: sensor.ups2_load
    to: unavailable
    for:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
condition: []
action:
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nut
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: homeassistant.reload_config_entry
    target:
      device_id:
        - e3402622bbdc3dc6fe3d5408c71658b1
        - 3e60c1162768bdc7f5c4efe7f42c657f
mode: single
```

which fixes the problem each time they go unavailable. Not sure what the problem is but the restart of the supervisor and reload of the integration fixes the problem for half a day or so.
This is the log when its starts up and is working fine:

```
[03:42:25] INFO: Setting mode to netserver...
[03:42:25] INFO: Connected USB devices:
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 009: ID 0658:0200 Sigma Designs, Inc. Aeotec Z-Stick Gen5 (ZW090) - UZB
Bus 002 Device 019: ID 0764:0501 Cyber Power System, Inc. CP1500 AVR UPS
Bus 002 Device 006: ID 0764:0501 Cyber Power System, Inc. CP1500 AVR UPS
Bus 002 Device 005: ID 1cf1:0030 Dresden Elektronik ZigBee gateway [ConBee II]
Bus 002 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 002 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 002 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
[03:42:25] INFO: Generating /etc/nut/upsd.users...
[03:42:25] INFO: Configuring user: ups
[03:42:25] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[03:42:25] INFO: Configuring Device named UPS1...
[03:42:25] INFO: Configuring Device named UPS2...
[03:42:25] INFO: Starting the UPS drivers...
Using subdriver: CyberPower HID 0.4
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Using subdriver: CyberPower HID 0.4
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[03:42:34] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.000215	listening on 0.0.0.0 port 3493
   0.000381	Connected to UPS [UPS2]: usbhid-ups-UPS2
   0.000415	Connected to UPS [UPS1]: usbhid-ups-UPS1
[03:42:34] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000098	Using power down flag file /etc/killpower
   0.000160	UPS: UPS1@localhost (master) (power value 1)
   0.000179	UPS: UPS2@localhost (master) (power value 1)
   0.000194	debug level is '1'
   0.000196	Warning: running as one big root process by request (upsmon -p)
   0.000289	Init SSL without certificate database
   0.001900	Trying to connect to UPS [UPS1@localhost]
   0.312064	User upsmonmaster@127.0.0.1 logged into UPS [UPS1]
   0.002532	Logged into UPS UPS1@localhost
   0.002756	Trying to connect to UPS [UPS2@localhost]
   0.312743	User upsmonmaster@127.0.0.1 logged into UPS [UPS2]
   0.003214	Logged into UPS UPS2@localhost
```

**Comment by sinclairpaul** [comment]
I would suggest not using auto as a port for multiple device.  More information can be found in the NUT documentation for that driver at https://networkupstools.org/docs/man/usbhid-ups.html

Please also capture the error from the addon log.

**Comment by DanDon** [comment]
What ports would I use and how would they be indivdually configured?

The errors I get are these:

```
59901.058126	Poll UPS [UPS1@localhost] failed - Data stale
59906.058679	Poll UPS [UPS1@localhost] failed - Data stale
59911.059123	Poll UPS [UPS1@localhost] failed - Data stale
59916.059619	Poll UPS [UPS1@localhost] failed - Data stale
59921.061097	Poll UPS [UPS1@localhost] failed - Data stale
59926.061574	Poll UPS [UPS1@localhost] failed - Data stale
59931.062069	Poll UPS [UPS1@localhost] failed - Data stale
59936.062550	Poll UPS [UPS1@localhost] failed - Data stale
59941.062988	Poll UPS [UPS1@localhost] failed - Data stale
59946.063483	Poll UPS [UPS1@localhost] failed - Data stale
59951.063924	Poll UPS [UPS1@localhost] failed - Data stale
59956.064451	Poll UPS [UPS1@localhost] failed - Data stale
59961.064927	Poll UPS [UPS1@localhost] failed - Data stale
59966.065365	Poll UPS [UPS1@localhost] failed - Data stale
59971.065828	Poll UPS [UPS1@localhost] failed - Data stale
59976.066190	Poll UPS [UPS1@localhost] failed - Data stale
59981.066841	Poll UPS [UPS1@localhost] failed - Data stale
59986.067290	Poll UPS [UPS1@localhost] failed - Data stale
59991.067779	Poll UPS [UPS1@localhost] failed - Data stale
59996.068266	Poll UPS [UPS1@localhost] failed - Data stale
60000.382582	Send ping to UPS [UPS1] failed: Resource temporarily unavailable
60001.068732	60001.378370	Connected to UPS [UPS1]: usbhid-ups-UPS1
Poll UPS [UPS1@localhost] failed - Driver not connected
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
60028.385359	Data for UPS [UPS1] is stale - check driver
60031.073580	Poll UPS [UPS1@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
60036.074082	Poll UPS [UPS1@localhost] failed - Data stale
60041.074567	Poll UPS [UPS1@localhost] failed - Data stale
60046.075011	Poll UPS [UPS1@localhost] failed - Data stale
60051.075524	Poll UPS [UPS1@localhost] failed - Data stale
60056.076992	Poll UPS [UPS1@localhost] failed - Data stale
60061.077474	Poll UPS [UPS1@localhost] failed - Data stale
60066.077981	Poll UPS [UPS1@localhost] failed - Data stale
60071.078428	Poll UPS [UPS1@localhost] failed - Data stale
60076.078885	Poll UPS [UPS1@localhost] failed - Data stale
60081.079379	Poll UPS [UPS1@localhost] failed - Data stale
60086.079852	Poll UPS [UPS1@localhost] failed - Data stale
60091.080329	Poll UPS [UPS1@localhost] failed - Data stale
60096.080845	Poll UPS [UPS1@localhost] failed - Data stale
```

**Comment by sinclairpaul** [comment]
Check the Implementation section of the linked documentation.  If you need assistance in configuration, I would suggest the forums or Discord would be a better place.  We use Github for tracking issues.

**Comment by gordonthree** [comment]
I am seeing the same issue, but it happens in 2-3 hours, not 8-14 as OP noticed. Log entries look the same as what was previously posted.

From advice of @sinclairpaul  I further identified my UPS by placing vendor id in the config file.  The addon will not accept the config file without ```port: auto``` being present.

```
devices:
  - name: Office
    driver: usbhid-ups
    config:
      - vendorid = 0764
    port: auto
mode: netserver
shutdown_host: 'true'
users:
  - actions: []
    instcmds:
      - all
    password: xxxxxxx
    username: xxxxxxx
loglevel: debug
list_usb_devices: true
```

**Comment by DanDon** [comment]
> I am seeing the same issue, but it happens in 2-3 hours, not 8-14 as OP noticed. Log entries look the same as what was previously posted.
> 
> From advice of @sinclairpaul I further identified my UPS by placing vendor id in the config file. The addon will not accept the config file without `port: auto` being present.
> 
> ```
> devices:
>   - name: Office
>     driver: usbhid-ups
>     config:
>       - vendorid = 0764
>     port: auto
> mode: netserver
> shutdown_host: 'true'
> users:
>   - actions: []
>     instcmds:
>       - all
>     password: xxxxxxx
>     username: xxxxxxx
> loglevel: debug
> list_usb_devices: true
> ```

Same issue.

I can not configure the devices without adding port auto ... this seems to be an add-on issue as the UPS devices work perfectly on the machine and all the problems are fixed when the add-on is restarted ... for a few hours. Then it fails again.

The watchdog doesn't pick up the failed devices though, to restart the add-on, as the add-on itself is still running but the connected devices aren't working

**Comment by drooff** [comment]
Same issue here - it works for 2-3 hours, then fails. Running latest version 0.9.0.

Config:

```
devices:
  - config: []
    driver: usbhid-ups
    name: ServerUPS
    port: auto
mode: netserver
shutdown_host: 'false'
users:
  - actions: []
    instcmds:
      - all
    password: <redacted>
    username: <redacted>
```

Startup log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2021.12.7
 Home Assistant Supervisor: 2021.12.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[14:31:18] INFO: Setting mode to netserver...
[14:31:18] INFO: Generating /etc/nut/upsd.users...
[14:31:18] INFO: Configuring user: <redacted>
[14:31:19] INFO: Configuring Device named ServerUPS...
[14:31:19] INFO: Starting the UPS drivers...
Using subdriver: CyberPower HID 0.4
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 0.
[cont-init.d] nutclient.sh: executing... 
[cont-init.d] nutclient.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:31:20] INFO: Starting the UPS information server...
   0.000000	fopen /run/nut/upsd.pid: No such file or directory
   0.000907	listening on 0.0.0.0 port 3493
   0.002034	Connected to UPS [ServerUPS]: usbhid-ups-ServerUPS
[14:31:20] INFO: Starting the UPS monitor and shutdown controller...
   0.000000	fopen /run/nut/upsmon.pid: No such file or directory
   0.000211	Using power down flag file /etc/killpower
   0.000420	UPS: ServerUPS@localhost (master) (power value 1)
   0.000495	debug level is '1'
   0.000550	Warning: running as one big root process by request (upsmon -p)
   0.000822	Init SSL without certificate database
   0.002715	Trying to connect to UPS [ServerUPS@localhost]
   0.015265	User upsmonmaster@127.0.0.1 logged into UPS [ServerUPS]
   0.003751	Logged into UPS ServerUPS@localhost
```

Log when failed:

```
8580.956423	Poll UPS [ServerUPS@localhost] failed - Data stale
8585.956934	Poll UPS [ServerUPS@localhost] failed - Data stale
8590.957441	Poll UPS [ServerUPS@localhost] failed - Data stale
8595.957794	Poll UPS [ServerUPS@localhost] failed - Data stale
8600.959600	Poll UPS [ServerUPS@localhost] failed - Data stale
8605.960141	Poll UPS [ServerUPS@localhost] failed - Data stale
8610.960682	Poll UPS [ServerUPS@localhost] failed - Data stale
8615.961187	Poll UPS [ServerUPS@localhost] failed - Data stale
8620.961748	Poll UPS [ServerUPS@localhost] failed - Data stale
8625.962249	Poll UPS [ServerUPS@localhost] failed - Data stale
8631.478021	8630.962754	Poll UPS [ServerUPS@localhost] failed - Data stale
Send ping to UPS [ServerUPS] failed: Resource temporarily unavailable
8631.836361	Connected to UPS [ServerUPS]: usbhid-ups-ServerUPS
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
8648.231793	Data for UPS [ServerUPS] is stale - check driver
8650.965439	Poll UPS [ServerUPS@localhost] failed - Data stale
{"message": "Event nut.ups_event fired."}Network UPS Tools upsmon 2.7.4
8655.966314	Poll UPS [ServerUPS@localhost] failed - Data stale
8660.966791	Poll UPS [ServerUPS@localhost] failed - Data stale
8665.967328	Poll UPS [ServerUPS@localhost] failed - Data stale
8670.967799	Poll UPS [ServerUPS@localhost] failed - Data stale
8675.968309	Poll UPS [ServerUPS@localhost] failed - Data stale
8680.968697	Poll UPS [ServerUPS@localhost] failed - Data stale
8685.969201	Poll UPS [ServerUPS@localhost] failed - Data stale
8690.969702	Poll UPS [ServerUPS@localhost] failed - Data stale
8695.970201	Poll UPS [ServerUPS@localhost] failed - Data stale
8700.970736	Poll UPS [ServerUPS@localhost] failed - Data stale
8705.971187	Poll UPS [ServerUPS@localhost] failed - Data stale
```
