### ISSUE TITLE
Increase polling interval

### ISSUE THREAD

**Issue by abrileroux** [hassio-addons/addon-nut#22]
Hi there,

I've hassio on a rpi 3. I have a Mecer UPS connected via USB. 

# Problem/Motivation
When the UPS state changes from OL to OB it sometimes takes over a minute before the sensor registers a change.

Is there any way to increase the polling frequency?

When I have a power failure I use the state change to turn some emergency/backup lights on. 

My configuration for NUT is : 
```
users:
  - username: xxxx
    password: xxxx
    instcmds:
      - all
    actions: []
devices:
  - name: mecer
    driver: nutdrv_qx
    port: auto
    config:
      - vendorid = 0665
      - productid = 5161
      - subdriver = cypress
      - protocol = mustek
mode: netserver
shutdown_hassio: 'false'
list_usb_devices: 'true'

```
