### ISSUE TITLE
eaton-3s-550  "No matching HID UPS found" on v0.10.0

### ISSUE THREAD

**Issue by Squale76** [hassio-addons/addon-nut#222]
# Problem

After upgrading from **v0.9.1** to **v0.10.0**, my Eaton 3S 550 is no longer recognized.
Before the upgrade, my UPS was working fine with the Network UPS Tools addon and the same configuration.

## My Configuration

```yaml
devices:
  - name: eaton-3s-550
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 0463
mode: netserver
shutdown_host: 'false'
users:
  - username: <username>
    password: <password>
    instcmds:
      - all
    actions: []
log_level: debug
list_usb_devices: true
```

## The Logs

```log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] nut: applying... 
[fix-attrs.d] nut: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.10.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.3.6
 Home Assistant Supervisor: 2022.03.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nut.sh: executing... 
[18:20:16] INFO: Setting mode to netserver...
[18:20:16] INFO: Connected USB devices:
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 011: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
Bus 001 Device 012: ID 0463:ffff MGE UPS Systems UPS
Bus 001 Device 009: ID 2101:8501 ActionStar USB HID
Bus 001 Device 008: ID 2101:8500 ActionStar USB2.0 Hub
Bus 001 Device 007: ID 152d:2338 JMicron Technology Corp. / JMicron USA Technology Corp. JM20337 Hi-Speed USB to SATA & PATA Combo Bridge
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[18:20:16] INFO: Generating /etc/nut/upsd.users...
[18:20:17] INFO: Configuring user: <username>
[18:20:17] DEBUG: Password SHA1: <password_sha1>
[18:20:18] DEBUG: Requested API resource: https://api.pwnedpasswords.com/range/9AED8
[18:20:18] DEBUG: API HTTP Response code: 200
[18:20:18] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[18:20:19] INFO: Configuring Device named eaton-3s-550...
[18:20:19] INFO: Starting the UPS drivers...
   0.000000	Starting UPS: eaton-3s-550
Network UPS Tools - Generic HID driver 0.41 (2.7.4)
USB communication driver 0.33
No matching HID UPS found
   0.051729	Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.7.4
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

## My Question

- Is there a regression on this model?
- With the new version v0.10.0, is there a configuration change to make that I haven't seen?

Thanks for your help

**Comment by sinclairpaul** [comment]
Looks to be an upstream issue with ARM and newer OS versions.

The suggestion there that I can see is to remove the vendor ID from the config.

The addon installs the packages and wraps the software that is provided by NUT.

**Comment by SylvainSimplonGit** [comment]
If I remove "config:" and "vendorid...", I've an error :
```log
Échec de l'enregistrement de la configuration du module complémentaire, Missing option 'config' in devices in Network UPS Tools (a0d7b954_nut). Got {'devices': [{'name': 'eaton-3s-550', 'driver': 'usbhid-ups', 'port': 'auto'}], 'mode': 'netserver', 'shutdown_host': 'false', 'users': [{'username': '<username>', 'password': '<password>', 'instcmds': ['all'], 'actions': []}], 'log_level': 'debug', 'list_usb_devices': True
```

**Comment by SylvainSimplonGit** [comment]
With this `config`, I've the samedi first error :
```yaml
devices:
  - name: eaton-3s-550
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: 'false'
users:
  - username: <username>
    password: <password>
    instcmds:
      - all
    actions: []
log_level: debug
list_usb_devices: true
```
