### ISSUE TITLE
Cyberpower 1500va ups goes to unavailable randomly after a few minutes.

### ISSUE THREAD

**Issue by jatgm1** [hassio-addons/addon-nut#245]
# Problem/Motivation

Whenever I try to use USB and the default settings for my cyberpower ups system it has some issue and the logs just say
[ups3@localhost] failed - Data stale
10350.947242 Poll UPS [ups3@localhost] failed - Data stale
10355.948000 Poll UPS [ups3@localhost] failed - Data stale
10360.948760 Poll UPS [ups3@localhost] failed - Data stale
10365.949554 Poll UPS [ups3@localhost] failed - Data stale

Over and over, not sure why. It works initially then goes to unavailable and the addon throws some random issue.

name: ups3
driver: usbhid-ups
port: auto
config:
serial = CXXLV7010181
This is the configuration. Not sure why. Super annoying. Their are two other ups systems (apc) working fine and dandy.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by marlonqpa** [comment]
Hi
I've also have Cyber Power ups and for me this config works:

```
devices:
  - name: qnapups
    driver: usbhid-ups
    port: auto
    config:
      - pollinterval = 15
mode: netserver
shutdown_host: "false"
users:
  - username: "!secret nut_user"
    password: "!secret nut_pass"
    instcmds:
      - all
    actions: []
upsd_maxage: 25
upsmon_deadtime: 25
```
