### ISSUE TITLE
Network UPS Tools  (NUT)  connection problem with Network UPS (SNMP)

### ISSUE THREAD

**Issue by foux44** [hassio-addons/addon-nut#255]
# Problem/Motivation

Using Home Assistant (2022.11.2 - Doker) and NUT (0.11.0) on Raspberry PI3 (Buster), I want to supervised my Network UPS (S2S Syrius MS 6000 from Legrand - [ms_ii_en.pdf](https://github.com/hassio-addons/addon-nut/files/9989430/ms_ii_en.pdf)) thanks to SNMP protocol.

I used the following pameter for the NUT Configuration: 

```
devices:
  - name: S2S_6000
    driver: snmp-ups
    port: 192.168.1.155
    mibs: ietf
    community: Rasp
    snmp_version: v3
    pollfreq: 15
    secLevel: authNoPriv
    secName: admin
    config:
      - desc = "APC Smart-UPS 6000VA"
mode: netserver
shutdown_host: false
users:
  - actions: []
    instcmds:
      - all
    username: admin
    password: MyPassWord
remote_ups_host: 192.168.1.155
remote_ups_user: admin
remote_ups_password: MyUPSassword 
remote_ups_name: ONDULEUR-1
```

My UPS is equipped with a CS 131 Network card ([manual_CS121_en.pdf](https://github.com/hassio-addons/addon-nut/files/9989413/manual_CS121_en.pdf)) with RJ45 output.

I used the SNMP protocol V3 as show below, according to the manual to monitore the CS121 the Standard-MIB for UPS-systems, RFC1628, is generally to be integrated into your NMS. Bi the way, [NUT doc](https://networkupstools.org/docs/man/snmp-ups.html)  shows compatible MIBS with the RFC 1628:  **ietf** 

![SNMP pameter from UPS](https://user-images.githubusercontent.com/101520604/201321915-9e0f5097-4ead-4497-b1c2-7badfb6b8786.jpg)

> (Why the issue was filed)

No solution was found in the NUT issues ...

## Expected behavior

 NUT server should keep alive.

> (What you expected to happen)

I want to be able to declare NUT server into home assistant thanks to the windows below

![NUT INTEGRATION](https://user-images.githubusercontent.com/101520604/201323042-872ad3f2-8158-4f89-8aea-0ba1bebc271b.jpg)

## Actual behavior

[Network UPS Tools_log.txt](https://github.com/hassio-addons/addon-nut/files/9989363/Network.UPS.Tools_log.txt)

> (What actually happened)
The NUIT log show that error:

```
Network UPS Tools - UPS driver controller 2.7.4
Startup timer elapsed, continuing...
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

## Steps to reproduce

I've tried several parameters, 
I've installed the following requirements as well:

- You will need to install the Net-SNMP package from http://www.net-snmp.org/ before building this driver.
- SNMP v3 also requires OpenSSL support from http://www.openssl.org/.

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,

> describe the rationale behind it)
