### ISSUE TITLE
SNMP configuration

### ISSUE THREAD

**Issue by kkellner** [hassio-addons/addon-nut#28]
How do you configure for SNMP?   

I have tried the following (I got config params from https://networkupstools.org/docs/man/snmp-ups.html)

```
users:
  - username: myusername
    password: mypassword
    instcmds:
      - all
    actions: []
devices:
  - name: apcups
    driver: snmp-ups
    port: 172.20.0.55
    config:
      snmp_version: v3
      secLevel: authPriv
      secName: snmpprofile1
      authPassword: myauthenticationpassphrase
      privPassword: myprivatepassphrase
mode: netserver
shutdown_host: 'false'
```

This results in:
```
[cont-init.d] nut.sh: executing... 
[19:45:41] INFO: Setting mode to netserver...
[19:45:41] INFO: Generating /etc/nut/upsd.users...
[19:45:41] INFO: Configuring user: myusername
[19:45:42] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[19:45:42] INFO: Configuring Device named apcups...
[19:45:42] INFO: Starting the UPS drivers...
Network UPS Tools - UPS driver controller 3.8.0-3220-g866b921892
Network UPS Tools - Generic SNMP UPS driver 0.97 (3.8.0-3220-g866b921892)
Driver exited abnormally
[cont-init.d] nut.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
```

<blockquote><div><strong><a href="https://networkupstools.org/docs/man/snmp-ups.html">snmp-ups(8)</a></strong></div></blockquote>

**Comment by sinclairpaul** [comment]
As I'm sure you can appreciate, we can't test and validate every UPS config out there.  Although in theory it should work from what I can see, is there a chance you could validate using SNMP v1/2 rather than V3?

**Comment by kkellner** [comment]
Yep, I and understand not having the ability to test all configurations.  I just wanted to check if you might know how SNMP can be configured.   I also tried v1 with the same result.  I also set logging to debug level and other then giving me some debug statements on `Pwned database` calls, it did not provide any additional information as to why `snmp-ups` is failing.

Is there any way to send/add "-DD" argument to `snmp-ups` executable to show detailed debug info?  E.g., `snmp-ups -DD`

SNMP v1 config:

```
devices:
  - name: apcups
    driver: snmp-ups
    port: 172.20.0.55
    config:
      community: public
      snmp_version: v1
      mibs: apcc
      pollfreq: 15
```

**Comment by sinclairpaul** [comment]
To get the addon to start, you can set the config to be something like:
```
devices:
  - name: myups
    driver: dummy-ups
    port: dummy.dev
    config: []
```

This would start using the dummy driver, you could then possibly exec into the container and run the nut executables from there.

**Comment by kkellner** [comment]
Does the plugin create the `ups.conf` file similar to below and run the below command?    I'll give the dummy command a shot.

The contents of the ups.conf file
```
[APC_UPS]
                   driver = snmp-ups
                   port = 172.20.0.55
                   snmp_version = v3
                   secLevel = authPriv
                   secName = snmpprofile1
                   authPassword = *********
                   authProtocol = MD5
                   privPassword = *********
                   privProtocol = DES
                   desc = "APC UPS"
```

Command:
`$ sudo /lib/nut/snmp-ups -DD -a APC_UPS`

**Comment by sinclairpaul** [comment]
We generate the ups.conf https://github.com/hassio-addons/addon-nut/blob/5715820841c8110d80f98e07d45ff078f22f0008/nut/rootfs/etc/cont-init.d/nut.sh#L72

Only run the -D on debug being set today, we could change this if needed:

https://github.com/hassio-addons/addon-nut/blob/5715820841c8110d80f98e07d45ff078f22f0008/nut/rootfs/etc/cont-init.d/nut.sh#L113

**Comment by kkellner** [comment]
I was able to exec into the container....    Editing the `/etc/nut/ups.conf` and running `/usr/lib/nut/snmp-ups -DD -a myups` worked fine.

Looks like the `config` param values are not getting set.

This is what I have in the config (for devices):

```
devices:
  - name: myups
    driver: dummy-ups
    port: dummy.dev
    config: []
  - name: apcups
    driver: snmp-ups
    port: 172.20.0.55
    config:
      snmp_version: v3
      secLevel: authPriv
      secName: snmpprofile1
      authPassword: myauthenticationpassphrase
      authProtocol: MD5
      privPassword: myprivatepassphrase
      privProtocol: DES
      desc: APC UPS
```
And here is what is in the `/etc/nut/ups.conf` file:

![image](https://user-images.githubusercontent.com/9540241/75840908-a5b18a00-5d89-11ea-885f-ba17df578a44.png)

**Comment by dale3h** [comment]
@kkellner Try an array of strings for the `config` option, like so:

```
devices:
  - name: myups
    driver: dummy-ups
    port: dummy.dev
    config: []
  - name: apcups
    driver: snmp-ups
    port: 172.20.0.55
    config:
      - snmp_version: v3
      - secLevel: authPriv
      - secName: snmpprofile1
      - authPassword: myauthenticationpassphrase
      - authProtocol: MD5
      - privPassword: myprivatepassphrase
      - privProtocol: DES
      - desc: APC UPS
```
