### ISSUE TITLE
PowerCool UPS: Device Not Supported 

### ISSUE THREAD

**Issue by cbear92** [hassio-addons/addon-nut#284]
# Problem/Motivation

Attempting to set up NUT server to manage USB connected PowerCool UPS. No matter what combination or permutation of configuration and drivers I have not been able to connect to the UPS - despite the UPS being supported by NUT, and the expected USB vendor/product info showing up in `lsusb`.

## Expected behavior

I expect that some combination of configuration options would allow the UPS to connect to the NUT server add-on, and for the resultant integration auto-discovery for the device.

## Actual behavior

Attempting different drivers yields slightly different results, but none of them connect to a supported device. This then leads to the add-on shutting down as no devices connected.

## Steps to reproduce

In the add-on configuration, using this .yaml code which is based on the parameters given on NUT site for this [manufacturer](https://networkupstools.org/stable-hcl.html) which is from filter UPS>PowerCool.
```
devices:
  - config:
      - port=auto
      - vendorid=0001
      - productid=0000
      - bus=001
      - product=MEC0003
      - protocol=hunnox
      - langid_fix=0x0409
      - novendor
      - norating
      - noscanlangid
    driver: nutdrv_qx
    name: ups-1
    port: auto
```
which gives the following error:
`Fatal error: 'noscanlangid' is not a valid flag for this driver.`

Removing that config flag then gives the main error:
```
Network UPS Tools - Generic Q* USB/Serial driver 0.28 (2.7.4)
USB communication driver 0.33
No supported devices found. Please check your device availability with 'lsusb'
Network UPS Tools - UPS driver controller 2.7.4
and make sure you have an up-to-date version of NUT. If this does not help,
try running the driver with at least 'subdriver', 'vendorid' and 'productid'
options specified. Please refer to the man page for details about these options
(man 8 nutdrv_qx).
```

Running lsusb shows the expected usb is present with the vendor and product id that has been specified:
`Bus 002 Device 003: ID 0001:0000 Fry's Electronics MEC0003`

Have then attempted to use different subdrivers [hennox, krauler, fabula] which result in the same error.

Have seen that other people have had issues with PowerColl UPS models in the past - both here and in the main NUT repo itself, but for the latter at least they have possibly fixed this manually by building from source directly. I am not particuarly confident in doing that in general, but also not too sure that's something that can be done for a HAOS add-on.

Anyone have any ideas?
