### ISSUE TITLE
NUT from community EDGE works, NUT from community don't.

### ISSUE THREAD

**Issue by sblantipodi** [hassio-addons/addon-nut#31]
# Problem/Motivation

Same config.
The NUT from community EDGE works, NUT from community don't.

## Expected behavior

that it work, some sensors should be visible

## Actual behavior

If I install the NUT addon from the community EDGE I can see all the sensors correctly working.
If I install the NUT addon from the comminity repo I see no sensors and I have some errors in the log.

> Platform nut not ready yet. Retrying in 60 seconds.
> 23:44:34 – Sensore (WARNING) - il messaggio si è verificato per la prima volta alle 23:43:23 e compare 2 volte
> NUT Sensor has no data, unable to set up
> 23:44:34 – nut (ERROR) - il messaggio si è verificato per la prima volta alle 23:42:42 e compare 3 volte
> Setup of sensor platform nut is taking over 10 seconds.
> 23:44:34 – Sensore (WARNING) - il messaggio si è verificato per la prima volta alle 23:42:42 e compare 3 volte
> Failure getting NUT ups alias, Socket error.
> 23:44:29 – nut (ERROR) - il messaggio si è verificato per la prima volta alle 23:42:37 e compare 3 volte

addon config:

> users:
>   - username: admin
>     password: XXX
>     instcmds:
>       - all
>     actions: []
> devices:
>   - name: myups
>     driver: usbhid-ups
>     port: auto
>     config: []
> mode: netserver
> shutdown_host: 'false'
> shutdown_hassio: 'false'

configuration.taml
```
sensor:
  - platform: nut
    scan_interval: 5
    name: "CyberPower PR1500ELCD"
    host: 40817795-nut
    username: user
    password: !secret nut
    resources:
      - ups.status.display
      - ups.timer.reboot
      - battery.voltage
      - ups.firmware.aux
      - ups.mfr
      - battery.runtime.low
      - ups.delay.shutdown
      - ups.load
      - ups.realpower.nominal
      - battery.charge.warning
      - battery.charge.low
      - ups.vendorid
      - ups.timer.shutdown
      - ups.test.result
      - ups.firmware
      - ups.productid
      - battery.runtime
      - battery.type
      - ups.model
      - ups.beeper.status
      - battery.charge
      - input.sensitivity
      - input.transfer.low
      - input.transfer.high
      - input.voltage
      - input.voltage.nominal
      - input.transfer.reason
      - output.current
      - output.frequency
      - output.voltage
      - output.voltage.nominal
```
