### ISSUE TITLE
NUT addon does not start

### ISSUE THREAD

**Issue by Railnolds** [hassio-addons/addon-nut#310]
### I used NUT addon some time. And one day I found that it is not working. I tried to reinstall it and now I get the error in log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices
-----------------------------------------------------------
 Add-on version: 0.12.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.6.3
 Home Assistant Supervisor: 2023.06.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.**
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
[12:44:05] INFO: Configuring timezone (Europe/Kiev)...
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nut.sh
[12:44:25] INFO: Setting mode to netserver...
[12:44:26] INFO: Generating /etc/nut/upsd.users...
[12:44:26] INFO: Configuring user: ups
[12:44:27] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[12:44:29] INFO: Configuring Device named myups...
[12:44:29] INFO: Starting the UPS drivers...
Network UPS Tools - Generic HID driver 0.47 (2.8.0)
USB communication driver (libusb 1.0) 0.43
libusb1: Could not open any HID devices: insufficient permissions on everything
No matching HID UPS found
Driver failed to start (exit status=1)
Network UPS Tools - UPS driver controller 2.8.0
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by gouthamravee** [comment]
Same problem here, I believe it was working before 2023.6 supervisor update but no hard proof unfortunately. 

I know in other cases I could fix this by doing a chmod on the usb devices /dev/bus/usb/... path but even with the ssh terminal tool that's not possible with HASS OS as the underlying OS is read only it seems.

**Comment by Railnolds** [comment]
> doing a chmod on the usb devices /dev/bus/usb/... path
Could you explain how to do it? Which is full path should be?

**Comment by gouthamravee** [comment]
As of HA version 2023.7.0 the NUTS addon is working again. I also rebooted the VM HASS is running on, even though I tried that earlier with no luck. 

Here's my NUTS config for HA in case 

```
- config:
    - serial = "4B1737P03171"
    - desc = "Network UPS 1"
    - vendorid = 051d*
  driver: usbhid-ups
  name: networkUPS1
  port: auto
  pollinterval: 1
- config:
    - serial = "4B1810P09778"
    - desc = "Network UPS 2"
    - vendorid = 051d*
  driver: usbhid-ups
  name: networkUPS2
  port: auto
  pollinterval: 1
- config:
    - serial = "CTHGY2005146"
    - desc = "Server UPS"
    - vendorid = 0764*
  driver: usbhid-ups
  name: serverUPS
  port: auto
  pollinterval: 1
```
