### ISSUE TITLE
NUT fails to start after upgrade to Home Assistant OS 10.4

### ISSUE THREAD

**Issue by OriginalResponsibleUser** [hassio-addons/addon-nut#317]
# Problem/Motivation

After upgrading to Home Assistant OS 10.4, the NUT addon no longer starts, seemingly due to a permission issue not allowing the UPS to be detected.
While I am currently running the 2023.8.0 beta this began when I was using 2023.7.3 (or possibly earlier, it was the release version that was out when HAOS 10.4 was released).

## Expected behavior

NUT should start and detect the UPS listed in the configuration file.

## Actual behavior

On startup the following logs appear.

 Add-on: Network UPS Tools
 Manage battery backup (UPS) devices

 Add-on version: 0.12.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.8.0b0
 Home Assistant Supervisor: 2023.07.2

s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[13:40:46] INFO: Configuring timezone (America/New_York)...
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/nut.sh
[13:40:47] INFO: Setting mode to netserver...
[13:40:47] INFO: Generating /etc/nut/upsd.users...
[13:40:47] INFO: Configuring user: hass
[13:40:47] DEBUG: Password SHA1: XXXXX
[13:40:47] DEBUG: Requested API resource: https://api.pwnedpasswords.com/range/XXXXX
[13:40:47] DEBUG: API HTTP Response code: 200
[13:40:47] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[13:40:48] INFO: Configuring Device named BackUPS1500...
[13:40:48] INFO: Configuring Device named BackUPS550...
[13:40:48] INFO: Starting the UPS drivers...
   0.000000	[D1] Starting UPS: BackUPS1500
Network UPS Tools - Generic HID driver 0.47 (2.8.0)
USB communication driver (libusb 1.0) 0.43
Using subdriver: APC HID 0.98
   0.273781	[D1] Starting UPS: BackUPS550
libusb1: Could not open any HID devices: insufficient permissions on everything
No matching HID UPS found
Network UPS Tools - Generic HID driver 0.47 (2.8.0)
USB communication driver (libusb 1.0) 0.43
Network UPS Tools - UPS driver controller 2.8.0
   0.499515	Driver failed to start (exit status=1)
cont-init: info: /etc/cont-init.d/nut.sh exited 1
cont-init: info: running /etc/cont-init.d/nutclient.sh
cont-init: info: /etc/cont-init.d/nutclient.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

## Steps to reproduce

I feel I have a fairly standard configuration file, so I believe this should be fairly reproducible.

## Configuration file
```yaml
users:
  - username: ****
    password: *********
    instcmds:
      - all
    actions: []
devices:
  - name: BackUPS1500
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 051d*
      - productid = 0002*
      - serial = abcd*
  - name: BackUPS550
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 051d*
      - productid = 0002*
      - serial = abcd*
mode: netserver
shutdown_host: false
log_level: debug
```
