### ISSUE TITLE
Permission denied /dev/ttyS0

### ISSUE THREAD

**Issue by DaAwesomeP** [hassio-addons/addon-nut#32]
# Problem/Motivation

Using a device on `/dev/ttyS0` gives permission denied.

## Expected behavior

It should be able to access all serial ports.

## Actual behavior

From addon log:
```
Unable to open /dev/ttyS0: Permission denied
  Current user id: nut (100)
Serial port owner: root (0)
Serial port group: audio (18)
     Mode of port: 0660
```

## Steps to reproduce

```
users:
  - username: redacted
    password: redacted
    instcmds:
      - all
    actions: []
devices:
  - name: ups1
    driver: powerpanel
    port: /dev/ttyS0
    config: []
mode: netserver
shutdown_host: 'false'
```

## Proposed changes

Please let me know if this is an issue with the supervisor and I should file this there instead (I suspect it might be).
