### ISSUE TITLE
UPS monitoring fails randomly with "Poll UPS [myups@localhost] failed - Data stale"

### ISSUE THREAD

**Issue by mdeweerd** [hassio-addons/addon-nut#342]
# Problem/Motivation

UPS monitoring stops working.
#258 does not seem to apply.

## Expected behavior

UPS monitoring should recover from issue.

## Actual behavior

```
1815092.070849	Poll UPS [myups@localhost] failed - Data stale
{"message":"Event nut.ups_event fired."}Network UPS Tools upsmon 2.8.0
1815097.072802	Poll UPS [myups@localhost] failed - Data stale
1815102.073765	Poll UPS [myups@localhost] failed - Data stale
1815107.074959	Poll UPS [myups@localhost] failed - Data stale
1815112.076173	Poll UPS [myups@localhost] failed - Data stale
1815117.076867	Poll UPS [myups@localhost] failed - Data stale
1815122.078012	Poll UPS [myups@localhost] failed - Data stale
1815127.079186	Poll UPS [myups@localhost] failed - Data stale
1815132.080387	Poll UPS [myups@localhost] failed - Data stale
1815137.081259	Poll UPS [myups@localhost] failed - Data stale
1815142.081916	Poll UPS [myups@localhost] failed - Data stale
1815147.084200	Poll UPS [myups@localhost] failed - Data stale
1815152.085375	Poll UPS [myups@localhost] failed - Data stale
1815157.086589	Poll UPS [myups@localhost] failed - Data stale
1815162.087291	Poll UPS [myups@localhost] failed - Data stale
1815167.088207	Poll UPS [myups@localhost] failed - Data stale
1815172.088724	Poll UPS [myups@localhost] failed - Data stale
```

## Steps to reproduce

No method found to reproduce.

No correlation to updates.

Here we can see that the system runs fin for a long time and fails uncorrelated to the states shown.

![image](https://github.com/hassio-addons/addon-nut/assets/1504752/c61d156d-6210-493f-8c97-fd929636a6a0)

## Proposed changes

- "Workaround": restart the add-on;
- Probable solution: monitor/reset/... USB connection.
- This applies randomly, I restart manually - maybe some automation could detect this and restart the add-on.

## Config

```yaml
users:
  - actions: []
    instcmds:
      - all
    username: USERNAME
    password: PASSWORD
devices:
  - config: []
    driver: usbhid-ups
    name: myups
    port: auto
mode: netserver
shutdown_host: "false"
list_usb_devices: true
```
