### ISSUE TITLE
Unstable experience with APC UPs

### ISSUE THREAD

**Issue by marcgarciamarti** [hassio-addons/addon-nut#354]
# Problem/Motivation
My experience with an APC UPS is bad. The UPS keeps reporting LB very frequently, even though I replaced the battery 1 month ago.

While this could be related to my unit being unhealthy, It looks like the standard nut component has issues with APC UPS: https://github.com/networkupstools/nut/issues/2347. The last post is mine. I echoed the issues reported by other APC owners running the native nut project, because I believe the HA add-on version does implement that native project in a containerized manner.

## Expected behavior

I expected to have stable telemetry that I could use to trigger healthy notifications. With my current experience, that is not an option at all.

## Actual behavior

APC devices might report unstable telemetry

## Steps to reproduce

Configure the integration like this:

```
users:
  - username: pass
    password: pwd
    instcmds:
      - all
    actions: []
devices:
  - name: apc-cs350
    driver: usbhid-ups
    port: auto
    config:
      - desc = "APC Back-UPS CS350"
      - vendorid = 051d

```

<img width="978" alt="Screenshot 2024-04-03 at 00 16 28" src="https://github.com/hassio-addons/addon-nut/assets/12695572/37594655-7ca3-4540-a572-5341116aef05">

<img width="1155" alt="Screenshot 2024-04-03 at 00 03 02" src="https://github.com/hassio-addons/addon-nut/assets/12695572/26efbb9d-f8d8-4207-b8ce-e1368ce40abb">
