### ISSUE TITLE
No NUT web interface when TCP port is exposed

### ISSUE THREAD

**Issue by barrelful** [hassio-addons/addon-nut#366]
# Problem/Motivation

I am configuring the addon with Network port 3493, causing the port to be forwarded.

When I try to access on the browser HAOS-IP:3493, I see:

```
ERR INVALID-ARGUMENT
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
ERR UNKNOWN-COMMAND
```

## Expected behavior

See a website with UPS info.

## Actual behavior

Errors from the description.

## Steps to reproduce

1. I install the addon, configure a device with:

   ```yaml
   devices:
     - name: "EatonEllipseECO"
       driver: usbhid-ups
       port: auto
       config:
         - vendorid = 0463
         - product = "Ellipse ECO"
         - productid = FFFF
   ```

1. Add user, password and network port. 
1. Start the addon.

## Proposed changes

Not sure what the problem is exactly. When I add the integration it seems to be getting some basic info (not sure how reliably it is working though).
