### ISSUE TITLE
NUT integration: using Sub-option: powervalue: 0 cause error starting add-on.

### ISSUE THREAD

**Issue by fmobile999** [hassio-addons/addon-nut#387]
### The problem

Problem: using Sub-option: `powervalue: 0`, due to documentation, cause error starting add-on.

Network UPS Tools
Current version: 0.13.2

```

Network UPS Tools upsmon 2.8.0

Fatal error: insufficient power configured!

Sum of power values........: 0
Minimum value (MINSUPPLIES): 1

Edit your upsmon.conf and change the values.
```

`powervalue: 1` works fine

Config:

```
- name: apcups
  driver: usbhid-ups
  port: auto
  powervalue: 0
  config:
    - vendorid = 051d*
```
  

### What version of Home Assistant Core has the issue?

core-2024.10.1

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

Network UPS Tools
