### ISSUE TITLE
Strange issue with missing sensors.

### ISSUE THREAD

**Issue by mattlward** [hassio-addons/addon-nut#41]
# Problem/Motivation
I am getting a couple of odd errors in my logs...
```
2020-05-14 09:53:22 WARNING (MainThread) [homeassistant.components.nut.sensor] Sensor type: output.current does not appear in the NUT status output, cannot add
2020-05-14 09:53:22 WARNING (MainThread) [homeassistant.components.nut.sensor] Sensor type: ups.temperature does not appear in the NUT status output, cannot add
```

> (Why the issue was filed)
Not asking for those values in my config and a grep of my complete config folder only finds the entries in the home-assistant.log file.
## Expected behavior

> (What you expected to happen)
Did not expect to see the entries.
## Actual behavior

> (What actually happened)

## Steps to reproduce

Not sure how to reproduce, but here are my nut configs...
```
- platform: nut
  alias: drups
  name: "DR UPS"
  username: 
  password: 
  host: 40817795-nut
  resources:
    - ups.load
    - battery.charge
    - input.voltage
    - battery.runtime
    - ups.status
    - ups.status.display
    
- platform: nut
  alias: lrups
  name: "LR UPS"
  username: 
  password:
  host: 192.168.1.203
  port: 3494
  resources:
    - ups.load
    - battery.charge
    - input.voltage
    - battery.runtime
    - ups.status
    - ups.status.display
```

I am running the latest version of HA with Hassio on Ubuntu in a docker install.  I have NUT version eafc871.  1 UPS is connected to the system via USB the other is a RPi acting as a remote NUT server connected to the UPS via USB.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
