### ISSUE TITLE
Error fetching UPS state

### ISSUE THREAD

**Issue by erkr** [hassio-addons/addon-nut#418]
The add on typically runs fine for several weeks, and then gets stuck with this error in HA:
``` 

Logger: homeassistant.components.nut
Source: helpers/update_coordinator.py:412
integration: Network UPS Tools (NUT) (documentation, issues)
First occurred: 00:05:21 (1 occurrences)
Last logged: 00:05:21

Error fetching NUT resource status data: Error fetching UPS state: Error running: LIST VAR mge: ERR DATA-STALE
``` 

In the add-on I see this in the log:
```
880344.260050	Poll UPS [mge@localhost] failed - Data stale
880349.260288	Poll UPS [mge@localhost] failed - Data stale
....
``` 
Just restarting the add-on resolves the issue. So the issue reported here is that the add-on doesn't recover (the incidental stale errors themselves are ok)

I increased the settings a little, but that only reduces the incident rate, but doesn't solve it:
```
upsd_maxage: 60
upsmon_deadtime: 40
```

**Comment by ricarva** [comment]
Same issue here, and tweaking pollinterval helped, but still run into the issue on certain UPS (CPS) state changes.

**Comment by erkr** [comment]
As a workaround I created an automation to restart the add-on:

``` 

- trigger:
  - platform: state
    entity_id: 
     - sensor.ups_status
  action:
   - if:
       - condition: template
         value_template: >
            {{ trigger.from_state.state != 'unavailable' 
             and trigger.to_state.state == 'unavailable' }}
     then:
       - action: notify.persistent_notification
         data:
            title: Attention
            message: UPS add-on restarted
       - action: hassio.addon_restart
         data:
           addon: a0d7b954_nut

```
