### ISSUE TITLE
Cyberpower 1500 reconnects USB on status change and Hassio gets Data stale

### ISSUE THREAD

**Issue by Electronlibre2012** [hassio-addons/addon-nut#55]
Hello @etatus

i have the exact same problem, when the UPS go in battery mode, the USB disconnected on my RPI4 and the info are unavailable to Hassio...

Have you find a solution for RPI4?

(dont want to go back to RPI3 to solve this lol).

Thanks

**Comment by etatus** [comment]
Just an ugly workaround. You can create an automation to detect when ups is disconnected and restart addon-nut to keep it working.

```
- id: 'xxxxxxxxxxxx'
  alias: UPS restart nut
  description: ''
  trigger:
  - platform: event
    event_type: nut.ups_event
  condition:
  - condition: state
    entity_id: sensor.cyberpower1500_status
    state: unavailable
  action:
  - data:
      addon: xxxxxxxx_nut
    service: hassio.addon_restart
  mode: single
```
