### ISSUE TITLE
Read-only file system Issue

### ISSUE THREAD

**Issue by SilvrrGIT** [hassio-addons/addon-nut#84]
# Problem/Motivation

> Nut Addon no longer starts. 

## Expected behavior

> Nut add-on should start and pull UPS data for HA consumption.  

## Actual behavior

> Nut Add-On log output ( https://pastebin.com/7U1jZSdv )

## Steps to reproduce

> I believe this happened after an upgrade to the 2021.02.05 supervisor though not 100% on that.  All my other add-ons are running OK, so opening a issue here and not in the supervisor repo.  The hardware ouput on the supervisor appears to have changed recently.

> I am running HassOS 5.11 (in an ESXi VM) and supervisor 2021.02.08 (same results on .06) and version 0.5.0 of the add-on (same results with 0.4.0)

```
  - name: 2-2.1
    sysfs: '/sys/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.1'
    dev_path: /dev/bus/usb/002/004
    subsystem: usb
    by_id: null
    attributes:
      BUSNUM: '002'
      DEVNAME: /dev/bus/usb/002/004
      DEVNUM: '004'
      DEVPATH: '/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.1'
      DEVTYPE: usb_device
      DRIVER: usb
      ID_BUS: usb
      ID_FOR_SEAT: usb-pci-0000_02_00_0-usb-0_2_1
      ID_MODEL: CP1500PFCLCD
      ID_MODEL_ENC: CP1500PFCLCD
      ID_MODEL_ID: '0501'
      ID_PATH: 'pci-0000:02:00.0-usb-0:2.1'
      ID_PATH_TAG: pci-0000_02_00_0-usb-0_2_1
      ID_REVISION: '0001'
      ID_SERIAL: CPS_CP1500PFCLCD_000000000000
      ID_SERIAL_SHORT: '000000000000'
      ID_USB_INTERFACES: ':030000:'
      ID_VENDOR: CPS
      ID_VENDOR_ENC: CPS
      ID_VENDOR_ID: '0764'
      MAJOR: '189'
      MINOR: '131'
      PRODUCT: 764/501/1
      SUBSYSTEM: usb
      TAGS: ':seat:'
      TYPE: 0/0/0
      USEC_INITIALIZED: '2561189'
```

## Proposed changes

> Sorry, not sure what the issue is so I can't provide any input
