### ISSUE TITLE
Working config broke by updating to 0.6

### ISSUE THREAD

**Issue by mdegat01** [hassio-addons/addon-nut#89]
# Problem/Motivation

I tried to update to version 0.6. After I did all of the sensors for my UPS became `unavailable`. I restored version 0.5 from a backup and they all came back and are working again.

## Expected behavior

I expected my sensors to continue functioning through the update.

## Actual behavior

All stopped updating. After the next HA restart they became `unavailable` with a `restored: true` status.

## Steps to reproduce
This is my config for the add-on:
```yaml
users:
  - username: <username>
    password: <password>
    instcmds:
      - all
    actions: []
devices:
  - name: myups
    driver: usbhid-ups
    port: auto
    config: []
mode: netserver
shutdown_host: true
list_usb_devices: true
log_level: debug
```
My UPS is a CyberPower CP1000PFCLCD. I configured the integration via the UI in Home Assistant.

## Proposed changes
Really don't know enough about how this all works to propose a fix here. Just would like to update without my sensors disappearing in HA since I rely on them.
