### ISSUE TITLE
Elevated commands inside of nut container, in console not working.

### ISSUE THREAD

**Issue by mattlward** [hassio-addons/addon-nut#95]
# Problem/Motivation

I am running the latest edge version to allow my Cyber Power UPS to be stable.  This command and others like it worked from inside the container via it's shell in Nut .0.5.0

[This thread]https://github.com/hassio-addons/addon-nut/issues/91  

Elevated nut commands do not work from within container shell.  Particularly uspcmd, works and lists commands that can be run.  
```
root@40817795-nut:/# upscmd -u upsmonmaster -p H8NzOjV30g471PF6TZtr -l DR_UPS
Instant commands supported on UPS [DR_UPS]:

beeper.disable - Disable the UPS beeper
beeper.enable - Enable the UPS beeper
beeper.mute - Temporarily mute the UPS beeper
beeper.off - Obsolete (use beeper.disable or beeper.mute)
beeper.on - Obsolete (use beeper.enable)
load.off - Turn off the load immediately
load.off.delay - Turn off the load with a delay (seconds)
load.on - Turn on the load immediately
load.on.delay - Turn on the load with a delay (seconds)
shutdown.return - Turn off the load and return when power is back
shutdown.stayoff - Turn off the load and remain off
shutdown.stop - Stop a shutdown in progress
test.battery.start.deep - Start a deep battery test
test.battery.start.quick - Start a quick battery test
test.battery.stop - Stop the battery test
```

But the following command fails to run:
```
root@40817795-nut:/# upscmd -u upsmonmaster -p H8NzOjV30g471PF6TZtr DR_UPS beeper.enable
Unexpected response from upsd: ERR ACCESS-DENIED
```
Any upscmd that requires operating at an elevated level fails. 

Addon config:
```
users:
  - username: upsmonmaster
    password: H8NzOjV30g471PF6TZtr
    instcmds:
      - all
    actions:
      - set
      - fsd
devices:
  - name: DR_UPS
    alias: drups
    driver: usbhid-ups
    port: auto
    config:
      - vendorid = 0764*
      - pollinterval = 15
mode: netserver
shutdown_host: 'false'
list_usb_devices: true
upsd_maxage: 25
upsmon_deadtime: 25
```

Reflected in a more of /etc/nut/upsd.users:
```
[upsmonmaster]
  password = CMxeAsK0OwGnrFmEX5ko
  upsmon master

[upsmonmaster]
  password = H8NzOjV30g471PF6TZtr
  instcmds = all
  actions = set
  actions = fsd
```
Oddly enough the addon also creates a upsmonmaster with no permissions.  May be the problem.
But, the config is indeed writing the file.

I am going to try creating another user in the Nut addon config to see if this resolves, user will have a different name.

## Expected behavior

I would expect the beeper to change state

## Actual behavior

> (What actually happened)
```
root@40817795-nut:/# upscmd -u upsmonmaster -p H8NzOjV30g471PF6TZtr DR_UPS beeper.enable
Unexpected response from upsd: ERR ACCESS-DENIED
```

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mattlward** [comment]
Creating a different user name in the addon config did the trick!
```
users:
  - username: admin
    password: pm9600sa
    instcmds:
      - all
    actions:
      - set
      - fsd
```

Reflected in the upsd.users file:
```
[upsmonmaster]
  password = 1wk6IvQnaJPoYNlsBCXE
  upsmon master

[admin]
  password = pm9600sa
  instcmds = all
  actions = set
  actions = fsd
```

Maybe this is expected behavior?
